### ISSUE TITLE
Data descriptor section is not handled

### ISSUE THREAD

**Issue by NeRdTheNed** [Col-E/LL-Java-Zip#17]
If bit 3 of the general purpose bit flag is set, local file headers have a 12 byte (no header) or 16 byte (with header 0x08074b50) section after compressed data (zip64 is slightly different). This data contains values for the CRC32, compressed size, and uncompressed size of the data (these values will be 0 in the normal location). See section 4.3.9 of [AppNote.txt](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) for more information. This causes 2 issues: 
- If this section is present, the values from it are not read. This results in them being 0.
- If this section is present when reading files with JvmZipReaderStrategy, the offset used in JvmLocalFileHeader does not take into account these extra bytes, causing it to read this section as part of the compressed data.

**Comment by NeRdTheNed** [comment]
Possibly related to #14.

**Comment by Col-E** [comment]
Fixed with #19 - Thank you 👍
